export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_TASK_BEING_EDITED = 'SET_TASK_BEING_EDITED';
export const EDIT_TASK_TITLE = 'EDIT_TASK_TITLE';
export const EDIT_TASK_DESCRIPTION = 'EDIT_TASK_DESCRIPTION';
export const CLEAR_TASK_BEING_EDITED = 'CLEAR_TASK_BEING_EDITED';