export const ADD_NOTE = 'ADD_NOTE';
export const UPDATE_NOTE = 'UPDATE_NOTE';
export const DELETE_NOTE = 'DELETE_NOTE';
export const UPDATE_NOTE_POSITION = 'UPDATE_NOTE_POSITION';
export const SET_USER_NOTE_COLOR = 'SET_USER_NOTE_COLOR';
export const SET_NOTE_BEING_EDITED = 'SET_NOTE_BEING_EDITED';
export const EDIT_NOTE_COLOR = 'EDIT_NOTE_COLOR';
export const EDIT_NOTE_TITLE = 'EDIT_NOTE_TITLE';
export const EDIT_NOTE_DESCRIPTION = 'EDIT_NOTE_DESCRIPTION';
export const CLEAR_NOTE_BEING_EDITED = 'CLEAR_NOTE_BEING_EDITED';


export const ADD_TASK = 'ADD_TASK';
export const UPDATE_TASK = 'UPDATE_TASK';
export const DELETE_TASK = 'DELETE_TASK';
export const SET_TASK_BEING_EDITED = 'SET_TASK_BEING_EDITED';
export const EDIT_TASK_TITLE = 'EDIT_TASK_TITLE';
export const EDIT_TASK_DESCRIPTION = 'EDIT_TASK_DESCRIPTION';
export const CLEAR_TASK_BEING_EDITED = 'CLEAR_TASK_BEING_EDITED';