name: Deploy task management app to development environment

# Controls when the action will run.
on:
  # Triggers the workflow on push events only for the main branch
  push:
    branches:
    - main

  # Triggers the workflow on closed pull request events only for the main branch
  pull_request:
    branches: [main]
    types: [closed]

  # Allows to run the workflow manually from the Actions tab
  workflow_dispatch:

# This workflow is made up of one job that calls the reusable workflow in graasp-deploy
jobs:
  graasp-deploy-s3-apps-workflow:
    name: Graasp app task management
    uses: graasp/graasp-deploy/.github/workflows/cintegration-s3-apps.yml@5ad156f86b2de177a81546db2ddc252a2ace36ca
    with:
      build-folder: 'build'
      version: 'latest'
    secrets:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_DEV }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_DEV }}
      aws-region: ${{ secrets.APPS_AWS_REGION }}
      aws-s3-bucket-name: ${{ secrets.AWS_S3_BUCKET_NAME_APPS_DEV }}
      cloudfront-distribution-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_APPS_DEV }}
      app-id: ${{ secrets.APP_ID }}
      graasp-domain: ${{ secrets.DEV_GRAASP_DOMAIN }}